// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Foot: typeof import('./components/Foot/Foot.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    LoginDialog: typeof import('./components/Header/LoginDialog.vue')['default']
    RegisterDialog: typeof import('./components/Header/RegisterDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
