server:
  port: 8888
  servlet:
    context-path: /jwt

token:
  # 密钥
  secret-key: 123kafkahiwhfakna0808234*)*)(
  # token 过期的秒数
  token-expire-second: "60"
  # http header 中请求头的前缀
  token-header-prefix: "Bearer "
  # 认证头的header名字
  authorization-header-name: "Authorization"
  # jwt 中 refresh token的过期时间
  refresh-token-expired-second: "120"
  # refresh header 的名字
  refresh-header-name: "Refresh-Token"
  # 用户唯一标识字段
  user-id: "userId"