// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleBox: typeof import('./components/Box/ArticleBox/ArticleBox.vue')['default']
    ArticleEditor: typeof import('./components/Write/articleEditor.vue')['default']
    ArticleLeft: typeof import('./components/Box/leftToolsBox/ArticleLeft.vue')['default']
    ArticleRight: typeof import('./components/Box/RightToolsBox/ArticleRight.vue')['default']
    CusCalendar: typeof import('./components/CusCalendar/index.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Foot: typeof import('./components/Foot/Foot.vue')['default']
    Index: typeof import('./components/Index/Index.vue')['default']
    Loading: typeof import('./components/Loading/Loading.vue')['default']
    Loading2: typeof import('./components/Loading/loading2.vue')['default']
    Login: typeof import('./components/Login/Login.vue')['default']
    MiniMessage: typeof import('./components/Box/RightToolsBox/miniMessage.vue')['default']
    Navigation: typeof import('./components/Navigation/Navigation.vue')['default']
    NavUserInfo: typeof import('./components/Navigation/NavUserInfo.vue')['default']
    RandomArticle: typeof import('./components/Box/RightToolsBox/randomArticle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopArticleBox: typeof import('./components/Box/TopArticleBox/TopArticleBox.vue')['default']
    Write: typeof import('./components/Write/Write.vue')['default']
  }
}

export {}
